import os

f = open("content.txt","r")
data = f.read()
print(data)
f.close()
print("###################################")
f = open("content.txt","r")
dataline = f.readline()
print(dataline)
f.close()
print("###################################")
f = open("sample.txt","w")
f.write("This is Line1")
f.close()
print("###################################")
f = open("sample.txt","a")
f.write("\nThis is Line2\nThis is Line3")
f.close()
print("###################################")
os.remove("delete.txt")
print("File deleted")