mytuples = (2, 4, 8, 7, 1, 2, 2)
mytuples1 = (1,)
mytuples2 = (1, 3, 4, 9, )
mytuples3 = (1)
mytuples4 = (12.4)
mytuples5 = ("Tuples")

print(mytuples)
print(type(mytuples))
print(mytuples.index(8))
print(mytuples.count(2))
print(mytuples1)
print(type(mytuples1))
print(mytuples2)
print(type(mytuples2))
print(mytuples3)
print(type(mytuples3))
print(mytuples4)
print(type(mytuples4))
print(mytuples5)
print(type(mytuples5))